[package]
name = "satellite_wallpaper"
version = "1.0.0"
authors = ["Jia Ye <planet0104@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
anyhow = "1"
once_cell = "1.7.2"
tiny_http = "0.8.2"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
windows = "0.10.0"
chrono = "0.4"
wallpaper = "2.0.1"
log = "0.4"
env_logger = "0.8.3"
dirs = "3.0"
serde_json = "1.0"
base64 = "0.13.0"
futures = "0.3.5"
minreq = { version="2.4.0", features=["https"]}
qrcode = "0.12.0"
local_ipaddress = "0.1.3"

[build-dependencies]
windows = "0.10.0"
winres = "0.1.11"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'

[package.metadata.winres]
OriginalFilename = "satellite_wallpaper.exe"
ProductName = "卫星壁纸"
ProductVersion = "1.0.0"
LegalCopyright = "Copyright © 2021 planet2@qq.com"